export const PODCAST_LIST_REQUEST = 'PODCAST_LIST_REQUEST';
export const PODCAST_LIST_SUCCESS = 'PODCAST_LIST_SUCCESS';
export const PODCAST_LIST_FAIL = 'PODCAST_LIST_FAIL';

export const PODCAST_DETAILS_REQUEST = 'PODCAST_DETAILS_REQUEST';
export const PODCAST_DETAILS_SUCCESS = 'PODCAST_DETAILS_SUCCESS';
export const PODCAST_DETAILS_FAIL = 'PODCAST_DETAILS_FAIL';
